name: Fetch INMET (UF única)

on:
  schedule:
    - cron: '25 12 * * *'   # 09:25 BRT
    - cron: '25 21 * * *'   # 18:25 BRT
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: pluviorn-inmet
  cancel-in-progress: true

env:
  TZ: America/Fortaleza
  UF: RN        # troque se quiser outra UF (ex.: CE, PB, PE)
  DIAS: 3       # janela de dias para garantir cobertura (recomendado 3)

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Coletar INMET (horário, últimas ${{ env.DIAS }} datas)
        run: node scripts/fetch-inmet.js

      - name: Snapshot com timestamp (UTC-3)
        run: |
          mkdir -p data
          TS=$(date +'%Y-%m-%d_%H%M')
          for ext in csv json; do
            if [ -s "data/latest.$ext" ]; then
              cp "data/latest.$ext" "data/${TS}.$ext"
            fi
          done
          ls -lh data | sed -n '1,200p' || true

      - name: Commit & Push
        run: |
          git config user.name "pluviorn-bot"
          git config user.email "actions@users.noreply.github.com"
          git add data/
          git commit -m "INMET (${UF}) atualização automática" || echo "Sem alterações"
          git push || true

      - name: Upload debug
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: inmet-datasets
          path: |
            data/inmet.json
            data/latest.json
            data/latest.csv
